# Generated by Django 5.2.7 on 2025-10-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talknest', '0003_remove_post_topic_community_post_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='community_banners/'),
        ),
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='community_logos/'),
        ),
    ]
