# Generated by Django 5.2.7 on 2025-10-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talknest', '0003_userprofile'),
        ('talknest', '0004_community_banner_community_logo'),
    ]

    operations = [
    ]
